"""The immutable experiment lock.

`experiment-state.json` is mutable working state. This module produces the separate,
write-once `experiment.lock`: the content-addressed record binding every identity a
later `execute` needs, emitted only at EXECUTION_FROZEN. Writing a different lock to
an existing path is refused rather than silently overwritten.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from tools.capsule.identity import PRODUCER, digest_of

LOCK_SCHEMA = "gnostoa-experiment-lock/v1"
LOCK_FILENAME = "experiment.lock"
# A lock is emitted while EXECUTION_FROZEN is still in progress. Its own completed
# receipt and the later READY receipt therefore cannot be part of the first lock and
# must not appear only on an otherwise-identical rerun.
_POST_LOCK_STAGE_RECEIPTS = frozenset({"EXECUTION_FROZEN", "READY_FOR_OWNER_REVIEW"})


class LockError(RuntimeError):
    """The lock cannot be written or is inconsistent with an existing lock."""


@dataclass(frozen=True, slots=True)
class ExperimentLock:
    payload: Mapping[str, object]

    @property
    def identity(self) -> str:
        return digest_of(dict(self.payload))

    def serialised(self) -> str:
        """The lock exactly as it is persisted, without persisting it."""
        return (
            json.dumps(
                {**self.payload, "lock_sha256": self.identity}, indent=2, sort_keys=True
            )
            + "\n"
        )

    def stage(self, root: Path) -> bytes:
        """Check immutability against the published lock and return bytes to publish.

        A lock is deliberately not written here. Emitting it directly would leave an
        immutable lock behind for a transaction that never commits, and that orphan
        then refuses every later attempt to reach the same readiness. Publication is
        the transaction's job, so the lock appears exactly when the state recording
        it does.
        """
        path = root / LOCK_FILENAME
        serialized = self.serialised()
        if path.is_file() and path.read_text().strip() != serialized.strip():
            raise LockError(
                "an experiment lock already exists with different content; a lock is "
                "immutable and is never silently overwritten"
            )
        return serialized.encode()

    def write(self, root: Path) -> Path:
        """Emit a lock directly, for materialisation outside a retained transaction.

        prepare() never uses this: inside a workspace transaction the lock is staged
        and published with the state that records it.
        """
        root.mkdir(parents=True, exist_ok=True)
        payload = self.stage(root)
        path = root / LOCK_FILENAME
        if not path.is_file():
            path.write_bytes(payload)
        return path


def build(
    *,
    experiment_id: str,
    question: str,
    claim_boundary: str,
    launch: Mapping[str, object],
    tasks: Sequence[Mapping[str, object]],
    capabilities: Sequence[Mapping[str, object]],
    stage_receipts: Mapping[str, str],
    authority: Mapping[str, object],
    run_plan: Mapping[str, object],
    artifact_store: str,
) -> ExperimentLock:
    """Bind every identity a later execute needs, with no rediscovery."""
    lock_receipts = {
        stage: receipt
        for stage, receipt in stage_receipts.items()
        if stage not in _POST_LOCK_STAGE_RECEIPTS
    }
    payload: dict[str, object] = {
        "schema": LOCK_SCHEMA,
        "producer": PRODUCER,
        "experiment": {
            "id": experiment_id,
            "question": question,
            "claim_boundary": claim_boundary,
        },
        "authority": dict(authority),
        "launch": dict(launch),
        "capabilities": [dict(item) for item in capabilities],
        "tasks": [dict(task) for task in tasks],
        "run_plan": dict(run_plan),
        # Where the content-addressed generated bytes are recoverable from.
        "artifact_store": artifact_store,
        "stage_receipts": lock_receipts,
    }
    return ExperimentLock(payload=payload)


def load_bytes(raw: bytes) -> Mapping[str, object]:
    """Decode and canonically validate a lock from bytes already in hand.

    Separated from `load` so a caller that has read the lock through its own contract
    -- a descriptor-bound retained read, say -- can apply exactly this validation
    without opening the path a second time. Declaring an identity and carrying it are
    different claims, and the recomputation below is what tells them apart. Every
    reader that decides anything about a lock has to make that distinction, or a lock
    execution would refuse can still prove a workspace ready.
    """
    try:
        decoded = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise LockError(f"lock is not readable json: {exc}") from exc
    if not isinstance(decoded, dict):
        raise LockError("lock is not an object")
    payload: Mapping[str, object] = decoded
    if payload.get("schema") != LOCK_SCHEMA:
        raise LockError(f"unsupported lock schema {payload.get('schema')!r}")
    recorded = payload.get("lock_sha256")
    recomputed = digest_of({k: v for k, v in payload.items() if k != "lock_sha256"})
    if recorded != recomputed:
        raise LockError("lock digest does not match its content")
    return payload


def load(path: Path) -> Mapping[str, object]:
    """Read and canonically validate the lock at this path."""
    return load_bytes(path.read_bytes())
