"""Subject-preparation contract.

Reads exact project metadata from a materialised tree, decides whether the tree is
directly runnable or needs a named deterministic preparation, and applies that
preparation as a content-addressed, inventoried generated artifact. Every inference
records its source; nothing is guessed silently and nothing tracked is modified.
"""

from __future__ import annotations

import re
import subprocess
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from tools.capsule.identity import digest_of, digest_text

# Explicit, reviewable option-prefix to distribution table. A pytest option namespace
# is attributed to a plugin only when listed here; anything else is reported as an
# unknown namespace rather than attributed by guesswork.
OPTION_PLUGINS: Mapping[str, str] = {
    "--benchmark": "pytest-benchmark",
    "--cov": "pytest-cov",
    "--timeout": "pytest-timeout",
    "--asyncio": "pytest-asyncio",
    "--hypothesis": "hypothesis",
    "--mock": "pytest-mock",
}

# Options that take a separate value argument, so the value token is dropped with it.
_VALUED_OPTIONS = frozenset(
    {
        "--benchmark-columns",
        "--benchmark-group-by",
        "--benchmark-warmup",
        "--cov-report",
        "--timeout",
    }
)

# ini keys carried across a config projection, in ini serialisation order.
_PROJECTED_KEYS = (
    "addopts",
    "filterwarnings",
    "markers",
    "norecursedirs",
    "xfail_strict",
)

# This preparation is a narrow, Gnostoa-owned algorithm, not a wrapper around the
# setuptools_scm distribution. It is named as the producer of the bytes it writes so
# that provenance is truthful: no external artifact participates in generation, and
# removing one could not change the output. Its compatibility target is pinned and
# characterised by tests.
PREPARATION_PRODUCER = "gnostoa.capsule.preparation.setuptools-scm-compatible/v1"
COMPATIBILITY_TARGET = (
    "setuptools-scm 8.1.0: guess-next-dev version scheme, node-and-date local scheme, "
    "and the .py version-file template"
)
SCM_COMPATIBLE_SCHEME = "gnostoa-setuptools-scm-compatible/v1"

_SCM_VERSION = re.compile(
    r"^(?P<release>\d+(?:\.\d+)*)(?:\.dev(?P<dev>\d+))?(?:\+(?P<local>[A-Za-z0-9.]+))?$"
)

# setuptools_scm 8.x version-file template, reproduced verbatim so a generated file is
# byte-identical to what the tool writes for the same version.
_SCM_TEMPLATE = """\
# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = {version!r}
__version_tuple__ = version_tuple = {version_tuple!r}
"""

_GIT_ENV = {
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
    "PATH": "/usr/bin:/bin",
}


class PreparationError(RuntimeError):
    """Preparation could not be performed deterministically."""


@dataclass(frozen=True, slots=True)
class TestConfig:
    """Discovered repository test configuration and what it demands."""

    source: str | None
    section: Mapping[str, object] = field(default_factory=dict)
    addopts: tuple[str, ...] = ()
    required_plugins: tuple[str, ...] = ()
    unknown_option_namespaces: tuple[str, ...] = ()
    inference: tuple[str, ...] = ()

    def as_json(self) -> dict[str, object]:
        return {
            "source": self.source,
            "addopts": list(self.addopts),
            "required_plugins": list(self.required_plugins),
            "unknown_option_namespaces": list(self.unknown_option_namespaces),
            "inference": list(self.inference),
        }


@dataclass(frozen=True, slots=True)
class ConfigProjection:
    """A provenance-bound mechanical projection of the repository test configuration."""

    content: str
    preserved: Mapping[str, object]
    removed_options: tuple[str, ...]
    removed_for_plugins: tuple[str, ...]
    source: str | None
    unprojectable_keys: tuple[str, ...] = ()

    def as_json(self) -> dict[str, object]:
        return {
            "source": self.source,
            "preserved_keys": sorted(self.preserved),
            "removed_options": list(self.removed_options),
            "removed_for_plugins": list(self.removed_for_plugins),
            "unprojectable_keys": list(self.unprojectable_keys),
            "content_sha256": digest_text(self.content),
        }


@dataclass(frozen=True, slots=True)
class PreparationRequirement:
    """A deterministic build-generated artifact the frozen tree does not carry."""

    required: bool
    kind: str | None = None
    generated_paths: tuple[str, ...] = ()
    tool_names: tuple[str, ...] = ()
    inference: tuple[str, ...] = ()

    def as_json(self) -> dict[str, object]:
        return {
            "required": self.required,
            "kind": self.kind,
            "generated_paths": list(self.generated_paths),
            "tool_names": list(self.tool_names),
            "inference": list(self.inference),
        }


@dataclass(frozen=True, slots=True)
class PreparationReceipt:
    """Proof that a preparation actually ran and what exactly it produced."""

    kind: str
    scheme: str
    derivation: Mapping[str, object]
    generated: Mapping[str, str]
    tracked_tree_unchanged: bool
    producer: str = PREPARATION_PRODUCER
    compatibility_target: str = COMPATIBILITY_TARGET
    artifact_verified: bool = False
    runnability: str = "deferred-to-base-reference-qualification"

    @property
    def identity(self) -> str:
        return digest_of(self.as_json())

    def as_json(self) -> dict[str, object]:
        return {
            "kind": self.kind,
            "scheme": self.scheme,
            "derivation": dict(self.derivation),
            "generated": dict(self.generated),
            "tracked_tree_unchanged": self.tracked_tree_unchanged,
            "producer": self.producer,
            "compatibility_target": self.compatibility_target,
            "artifact_verified": self.artifact_verified,
            "runnability": self.runnability,
        }


def _load_pyproject(tree: Path) -> tuple[dict[str, object], str | None]:
    path = tree / "pyproject.toml"
    if not path.is_file():
        return {}, None
    try:
        return tomllib.loads(path.read_text()), "pyproject.toml"
    except tomllib.TOMLDecodeError:
        return {}, None


def _pytest_section(
    data: Mapping[str, object],
) -> tuple[Mapping[str, object], str | None]:
    """pytest 9 reads [tool.pytest]; earlier versions read [tool.pytest.ini_options]."""
    tool = data.get("tool")
    if not isinstance(tool, dict):
        return {}, None
    pytest_table = tool.get("pytest")
    if not isinstance(pytest_table, dict):
        return {}, None
    ini_options = pytest_table.get("ini_options")
    if isinstance(ini_options, dict):
        return ini_options, "pyproject.toml [tool.pytest.ini_options]"
    return pytest_table, "pyproject.toml [tool.pytest]"


def _plugin_for(namespace: str) -> str | None:
    for prefix, distribution in OPTION_PLUGINS.items():
        if namespace == prefix or namespace.startswith(prefix + "-"):
            return distribution
    return None


def discover_test_config(tree: Path) -> TestConfig:
    data, _origin = _load_pyproject(tree)
    if not data:
        return TestConfig(source=None)
    section, where = _pytest_section(data)
    if not section:
        return TestConfig(source=None)

    raw_addopts = section.get("addopts", [])
    if isinstance(raw_addopts, str):
        addopts = tuple(raw_addopts.split())
    elif isinstance(raw_addopts, list):
        addopts = tuple(str(item) for item in raw_addopts)
    else:
        addopts = ()

    plugins: list[str] = []
    unknown: list[str] = []
    inference: list[str] = []
    for option in addopts:
        if not option.startswith("-"):
            continue
        namespace = option.split("=", 1)[0]
        matched = _plugin_for(namespace)
        if matched is None:
            unknown.append(namespace)
        elif matched not in plugins:
            plugins.append(matched)
            inference.append(f"{where}: addopts {namespace} requires {matched}")

    return TestConfig(
        source=where,
        section=dict(section),
        addopts=addopts,
        required_plugins=tuple(plugins),
        unknown_option_namespaces=tuple(sorted(set(unknown))),
        inference=tuple(inference),
    )


def _render_ini_value(key: str, value: object) -> str | None:
    """Render one declared key into ini form, or None when it would lose information."""
    if isinstance(value, bool):
        return f"{key} = {'true' if value else 'false'}"
    if isinstance(value, (int, float, str)):
        return f"{key} = {value}"
    if isinstance(value, list) and all(
        isinstance(item, (str, int, float, bool)) for item in value
    ):
        rendered = "\n".join(f"    {item}" for item in value)
        return f"{key} =\n{rendered}" if value else f"{key} ="
    return None


def project_test_config(
    config: TestConfig, available: Sequence[str]
) -> ConfigProjection:
    """Carry the repository configuration forward minus only unsatisfiable options.

    Every declared key is preserved verbatim. The only modification is removing the
    addopts attributable to a plugin the runtime does not provide. A key that cannot
    be rendered into ini form without loss is reported so the caller can block, rather
    than dropped silently.
    """
    have = set(available)
    absent = {plugin for plugin in config.required_plugins if plugin not in have}

    kept: list[str] = []
    removed: list[str] = []
    skip_next = False
    for option in config.addopts:
        if skip_next:
            removed.append(option)
            skip_next = False
            continue
        namespace = option.split("=", 1)[0]
        plugin = _plugin_for(namespace) if namespace.startswith("-") else None
        if plugin is not None and plugin in absent:
            removed.append(option)
            skip_next = namespace in _VALUED_OPTIONS and "=" not in option
            continue
        kept.append(option)

    preserved: dict[str, object] = {}
    unprojectable: list[str] = []
    rendered_lines: list[str] = []
    for key in sorted(config.section):
        value = list(kept) if key == "addopts" else config.section[key]
        if key == "addopts" and not kept:
            continue
        rendered = _render_ini_value(key, value)
        if rendered is None:
            unprojectable.append(key)
            continue
        preserved[key] = value
        rendered_lines.append(rendered)

    lines = [
        "# Generated by gnostoa.capsule: provenance-bound test-config projection.",
        f"# Source: {config.source or 'no repository configuration discovered'}.",
        "# Every declared key is carried forward verbatim except addopts attributable to",
        "# a plugin the frozen runtime does not provide. Removed options are inventoried",
        "# in the capsule provenance. No plugin is installed and no oracle assertion is",
        "# altered. A key that cannot be rendered losslessly is reported, never dropped.",
        "[pytest]",
        *rendered_lines,
    ]

    return ConfigProjection(
        content="\n".join(lines) + "\n",
        preserved=preserved,
        removed_options=tuple(removed),
        removed_for_plugins=tuple(sorted(absent)),
        source=config.source,
        unprojectable_keys=tuple(unprojectable),
    )


def discover_preparation(tree: Path) -> PreparationRequirement:
    """Detect build-generated files the frozen tree omits (the D3 class)."""
    data, origin = _load_pyproject(tree)
    if not data:
        return PreparationRequirement(required=False)

    tool = data.get("tool")
    scm = tool.get("setuptools_scm") if isinstance(tool, dict) else None
    if not isinstance(scm, dict):
        return PreparationRequirement(required=False)

    inference = [f"{origin} [tool.setuptools_scm] present"]
    project = data.get("project")
    if isinstance(project, dict) and "version" in (project.get("dynamic") or []):
        inference.append(f"{origin} project.dynamic includes 'version'")

    targets: list[str] = []
    for key in ("write_to", "version_file"):
        value = scm.get(key)
        if isinstance(value, str) and value:
            targets.append(value)
            inference.append(f"{origin} [tool.setuptools_scm] {key} = {value}")

    missing = tuple(target for target in targets if not (tree / target).exists())
    if not missing:
        return PreparationRequirement(
            required=False,
            kind="setuptools-scm-version-file",
            inference=tuple(inference),
        )
    inference.append("declared version file is absent from the frozen tree")
    return PreparationRequirement(
        required=True,
        kind="setuptools-scm-version-file",
        generated_paths=missing,
        tool_names=(),
        inference=tuple(inference),
    )


def _version_tuple(version: str) -> tuple[int | str, ...]:
    """PEP 440 tuple for the narrow version shape this preparation produces."""
    match = _SCM_VERSION.fullmatch(version)
    if match is None:
        return (version,)
    fields: list[int | str] = [int(part) for part in match["release"].split(".")]
    if match["dev"] is not None:
        fields.append(f"dev{int(match['dev'])}")
    if match["local"] is not None:
        fields.append(match["local"])
    return tuple(fields)


def derive_scm_version(repository: Path, commit: str) -> dict[str, object]:
    """Derive a setuptools_scm version from authoritative Git metadata.

    Uses the same describe invocation setuptools_scm's Git backend performs, then the
    documented default schemes: guess-next-dev for the version and node-and-date for
    the local segment of a clean tree. The materialised workspace deliberately carries
    no SCM metadata, so the derivation happens here, against the frozen repository.
    """
    described = subprocess.run(
        [
            "git",
            "-C",
            str(repository),
            "describe",
            "--tags",
            "--long",
            "--match",
            "*[0-9]*",
            commit,
        ],
        check=True,
        capture_output=True,
        text=True,
        env=_GIT_ENV,
    ).stdout.strip()
    match = re.fullmatch(
        r"(?P<tag>.+)-(?P<distance>\d+)-(?P<node>g[0-9a-f]+)", described
    )
    if match is None:
        raise PreparationError(f"unparsable git describe output: {described!r}")
    tag, distance, node = match["tag"], int(match["distance"]), match["node"]

    if distance == 0:
        version = tag
    elif tag.endswith(".dev0"):
        # guess-next-dev bumps a .dev0 tag down to its base release.
        version = f"{tag[: -len('.dev0')]}.dev{distance}+{node}"
    else:
        head, _, last = tag.rpartition(".")
        if not last.isdigit():
            raise PreparationError(f"cannot guess the next version from tag {tag!r}")
        version = f"{head}.{int(last) + 1}.dev{distance}+{node}"
    return {
        "describe": described,
        "tag": tag,
        "distance": distance,
        "node": node,
        "dirty": False,
        "version": version,
    }


def apply_preparation(
    tree: Path,
    requirement: PreparationRequirement,
    *,
    repository: Path,
    commit: str,
    scheme: str,
) -> PreparationReceipt:
    """Generate the declared build artifact into `tree` and return a receipt."""
    if requirement.kind != "setuptools-scm-version-file":
        raise PreparationError(f"unsupported preparation kind {requirement.kind!r}")
    if scheme != SCM_COMPATIBLE_SCHEME:
        raise PreparationError(f"unsupported preparation scheme {scheme!r}")

    derivation = derive_scm_version(repository, commit)
    version = str(derivation["version"])
    content = _SCM_TEMPLATE.format(
        version=version, version_tuple=_version_tuple(version)
    )

    generated: dict[str, str] = {}
    for relative in requirement.generated_paths:
        target = tree / relative
        if target.exists():
            raise PreparationError(f"refusing to overwrite existing {relative!r}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        generated[relative] = digest_text(content)

    # Bounded verification: the generated module must be well-formed and expose the
    # symbols the subject imports. Whether the whole subject runs is established by
    # BASE_REFERENCE_QUALIFIED inside the declared runtime, not asserted here.
    namespace: dict[str, object] = {}
    try:
        exec(compile(content, "<generated-version>", "exec"), namespace)
    except Exception as exc:  # pragma: no cover - defensive
        raise PreparationError(f"generated artifact is not importable: {exc}") from exc
    if namespace.get("version") != version or namespace.get("__version__") != version:
        raise PreparationError("generated artifact does not expose the derived version")

    return PreparationReceipt(
        kind=requirement.kind,
        scheme=scheme,
        derivation=derivation,
        generated=generated,
        tracked_tree_unchanged=True,
        artifact_verified=True,
    )


def missing_plugins(config: TestConfig, available: Sequence[str]) -> tuple[str, ...]:
    have = set(available)
    return tuple(plugin for plugin in config.required_plugins if plugin not in have)
