"""node-vitest adapter."""

from __future__ import annotations

from tools.capsule.adapters import Adapter, GeneratedFile, HarnessResult, Invocation
from tools.capsule.identity import provenance
from tools.capsule.preparation import TestConfig
from tools.capsule.spec import TaskSpec

CONFIG = "phase-d-vitest.config.mjs"
SETUP = "phase-d-preload.mjs"


class NodeVitestAdapter(Adapter):
    name = "node-vitest"

    def build(
        self,
        task: TaskSpec,
        *,
        workspace_path: str,
        oracle_name: str,
        test_config: TestConfig,
    ) -> HarnessResult:
        generated: list[GeneratedFile] = []
        setup_files: list[str] = []

        if task.harness.preload_modules:
            body = ["// Generated by gnostoa.capsule. Mechanical preload only."]
            body += [f"import {module!r}" for module in task.harness.preload_modules]
            generated.append(
                GeneratedFile(
                    path=SETUP,
                    content="\n".join(body) + "\n",
                    provenance=provenance(
                        {"preload_modules": list(task.harness.preload_modules), "task": task.id}
                    ),
                )
            )
            setup_files.append(SETUP)

        setup = f", setupFiles: {setup_files!r}" if setup_files else ""
        content = (
            "// Generated by gnostoa.capsule. Collects the frozen root-placed oracle,\n"
            "// whose own import path declares workspace-root placement. The repository\n"
            "// include glob cannot collect it. No oracle byte is altered.\n"
            "import { defineConfig } from 'vitest/config'\n"
            f"export default defineConfig({{ test: {{ include: [{oracle_name!r}]{setup} }} }})\n"
        )
        generated.append(
            GeneratedFile(
                path=CONFIG,
                content=content,
                provenance=provenance({"task": task.id, "oracle": oracle_name}),
            )
        )

        argv = ("vitest", "run", "--config", CONFIG, "--reporter=verbose")
        return HarnessResult(
            preload_modules=task.harness.preload_modules,
            generated_files=tuple(generated),
            invocation=Invocation(
                argv=argv + tuple(task.harness.extra_argv),
                cwd=workspace_path,
                env={"HOME": "/tmp"},
            ),
            added_runtime_packages=(),
            isolated_test_config=True,
        )
