"""python-pytest adapter."""

from __future__ import annotations

from tools.capsule.adapters import Adapter, GeneratedFile, HarnessResult, Invocation
from tools.capsule.identity import provenance
from tools.capsule.preparation import ConfigProjection, TestConfig, missing_plugins
from tools.capsule.spec import TaskSpec

CONFTEST = "conftest.py"
ISOLATED_INI = "phase-d-pytest.ini"

# Reserved qualification-only staging prefix. pytest derives a module name from the
# test file's path, so the staged name must be a plain Python identifier: an interior
# dot would be read as a dotted package path, and a leading digit, a keyword or the
# name of a real module would each fail or shadow subject code. Deriving the name from
# the oracle digest instead of sanitising the owner's basename makes it safe for every
# such basename at once, keeps it deterministic, and keeps it out of the subject's own
# namespace. The prefix is reserved: a collision fails closed rather than overwriting.
_STAGED_ORACLE_PREFIX = "_gnostoa_staged_oracle_"
_STAGED_DIGEST_CHARS = 32


class PythonPytestAdapter(Adapter):
    name = "python-pytest"

    def staged_oracle_name(self, oracle_sha256: str, source_name: str) -> str:
        return f"{_STAGED_ORACLE_PREFIX}{oracle_sha256[:_STAGED_DIGEST_CHARS]}.py"

    def build(
        self,
        task: TaskSpec,
        *,
        workspace_path: str,
        oracle_name: str,
        test_config: TestConfig,
        projection: ConfigProjection | None = None,
    ) -> HarnessResult:
        generated: list[GeneratedFile] = []
        blockers: list[dict[str, object]] = []

        preload = task.harness.preload_modules
        if preload:
            lines = [
                "# Generated by gnostoa.capsule. Mechanical preload only.",
                "# Binds submodules the oracle reaches by attribute but never imports.",
                "# No assertion, no subject modification, no dependency added.",
            ]
            lines += [f"import {module}  # noqa: F401" for module in preload]
            content = "\n".join(lines) + "\n"
            generated.append(
                GeneratedFile(
                    path=CONFTEST,
                    content=content,
                    provenance=provenance(
                        {"preload_modules": list(preload), "task": task.id}
                    ),
                )
            )

        argv: list[str] = ["python", "-m", "pytest"]
        isolated = task.harness.isolate_test_config
        absent = missing_plugins(test_config, task.runtime.available_plugins)

        if isolated:
            if projection is None:
                blockers.append(
                    {
                        "task": task.id,
                        "code": "test-config-projection-missing",
                        "detail": "isolation was requested without a computed config projection",
                    }
                )
            else:
                generated.append(
                    GeneratedFile(
                        path=ISOLATED_INI,
                        content=projection.content,
                        provenance=provenance(
                            {
                                "task": task.id,
                                "projected_from": projection.source,
                                "preserved_keys": sorted(projection.preserved),
                                "removed_options": list(projection.removed_options),
                                "removed_for_plugins": list(
                                    projection.removed_for_plugins
                                ),
                            }
                        ),
                    )
                )
                argv += ["-c", ISOLATED_INI]
        elif absent:
            blockers.append(
                {
                    "task": task.id,
                    "code": "test-config-requires-absent-plugin",
                    "detail": (
                        f"{test_config.source} injects options requiring {list(absent)}, which the "
                        "frozen runtime does not provide; declare harness.isolate_test_config or "
                        "qualify a runtime that provides them"
                    ),
                }
            )

        argv += [oracle_name, "-v", "-p", "no:cacheprovider"]
        argv += list(task.harness.extra_argv)

        return HarnessResult(
            preload_modules=preload,
            generated_files=tuple(generated),
            invocation=Invocation(
                argv=tuple(argv),
                cwd=workspace_path,
                env={"PYTHONDONTWRITEBYTECODE": "1", "HOME": "/tmp"},
            ),
            added_runtime_packages=(),
            isolated_test_config=isolated,
            blockers=tuple(blockers),
        )
