"""python-pytest adapter."""

from __future__ import annotations

from tools.capsule.adapters import Adapter, GeneratedFile, HarnessResult, Invocation
from tools.capsule.identity import provenance
from tools.capsule.preparation import TestConfig, missing_plugins
from tools.capsule.spec import TaskSpec

CONFTEST = "conftest.py"
ISOLATED_INI = "phase-d-pytest.ini"


class PythonPytestAdapter(Adapter):
    name = "python-pytest"

    def build(
        self,
        task: TaskSpec,
        *,
        workspace_path: str,
        oracle_name: str,
        test_config: TestConfig,
    ) -> HarnessResult:
        generated: list[GeneratedFile] = []
        blockers: list[dict[str, object]] = []

        preload = task.harness.preload_modules
        if preload:
            lines = [
                "# Generated by gnostoa.capsule. Mechanical preload only.",
                "# Binds submodules the oracle reaches by attribute but never imports.",
                "# No assertion, no subject modification, no dependency added.",
            ]
            lines += [f"import {module}  # noqa: F401" for module in preload]
            content = "\n".join(lines) + "\n"
            generated.append(
                GeneratedFile(
                    path=CONFTEST,
                    content=content,
                    provenance=provenance({"preload_modules": list(preload), "task": task.id}),
                )
            )

        argv: list[str] = ["python", "-m", "pytest"]
        isolated = task.harness.isolate_test_config
        absent = missing_plugins(test_config, task.runtime.available_plugins)

        if isolated:
            ini_lines = [
                "# Generated by gnostoa.capsule. Mechanical test-config isolation.",
                "# Prevents auto-discovery of repository options that require plugins the",
                "# frozen runtime intentionally does not provide. No plugin is installed and",
                "# no oracle assertion is altered.",
                "[pytest]",
            ]
            generated.append(
                GeneratedFile(
                    path=ISOLATED_INI,
                    content="\n".join(ini_lines) + "\n",
                    provenance=provenance(
                        {
                            "task": task.id,
                            "isolated_from": test_config.source,
                            "excluded_addopts": list(test_config.addopts),
                        }
                    ),
                )
            )
            argv += ["-c", ISOLATED_INI]
        elif absent:
            blockers.append(
                {
                    "task": task.id,
                    "code": "test-config-requires-absent-plugin",
                    "detail": (
                        f"{test_config.source} injects options requiring {list(absent)}, which the "
                        "frozen runtime does not provide; declare harness.isolate_test_config or "
                        "qualify a runtime that provides them"
                    ),
                }
            )

        argv += [oracle_name, "-v", "-p", "no:cacheprovider"]
        argv += list(task.harness.extra_argv)

        return HarnessResult(
            preload_modules=preload,
            generated_files=tuple(generated),
            invocation=Invocation(
                argv=tuple(argv),
                cwd=workspace_path,
                env={"PYTHONDONTWRITEBYTECODE": "1", "HOME": "/tmp"},
            ),
            added_runtime_packages=(),
            isolated_test_config=isolated,
            blockers=tuple(blockers),
        )
